// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	Datetime    time.Time
	Title       string
	Description sql.NullString
	Status      string
	CreatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	Phone        string
	IsAdmin      sql.NullBool
	CreatedAt    time.Time
}
